server:
  port: 8877

logs:
  directory: logs

security:
  ssl:
    active: false
    key: privatekey.pem
    ca: COMODORSADomainValidationSecureServerCA.crt
    cert: finviet.com.vn.crt

  rateLlmit:
    maxRequest: 0
    resetAfter: 3600000

  requestTracker:
    maxCache: 10

jwt:
  secret: loyalty_secret_dev

activemq:
  client:
  server:
    host: 10.11.30.30
    port: 61613
    login: admin
    passcode: admin
  queues:
    ewalletNotification: /topic/EWALLET_NOTIFY

redis:
  host: 127.0.0.1
  port: 6379
  password: ''
  expireIn: 300

addon:
  fvBackend:
    api: http://sandbox.finviet.com.vn:3980
    version: 2.0

database:
- name: "default"
  type: "mysql"
  logging: true
  synchronize: false
  entities:
  - "dist/entities/*.{js,ts}"
  replication:
    master:
      host: "10.50.50.5"
      port: 3308
      username: "finviet"
      password: "yVREMIiso8BYPBAptGS8"
      database: "loan_referral"
    slaves:
    - host: "10.50.50.5"
      port: 3308
      username: "finviet"
      password: "yVREMIiso8BYPBAptGS8"
      database: "loan_referral"

mafc_api:
  partner_code: 'FIV'
  input_data_entry:
    url: 'https://apigw-staging.mafc.vn/dataentry-mci'
    username: 'dataentrymci'
    password: 'mirae52345!@#%$'
  master_data:
    url: 'https://apigw-staging.mafc.vn/masterdatamci'
    username: 'masterdatamci'
    password: 'mafc32412^&%^$'
  check_customer_info:
    url: 'https://apigw-staging.mafc.vn/3p/v2/check-customer'
    username: 'mirae-3p'
    password: '123456'
  cic:
    url: 'https://apigw-staging.mafc.vn/cic'
    username: 'mirae-3p'
    password: '123456'
  upload:
    push_to_und_url: 'https://apigw-staging.mafc.vn/dataentry/openapi/pushUnderSystem'
    reply_defer_url: 'https://apigw-staging.mafc.vn/dataentry/openapi/pushPenHistory'
    username: 'dataentry'
    password: 'mafcdataentry$%&$!@#'

upload:
  backendUrl: http://sandbox.finviet.com.vn:3000/upload
  backendUser: loan_referral-user

download:
  backendUrl: http://sandbox.finviet.com.vn:3000/download
  backendUser: loan_referral-user
  token: dvsdvsdkvmvkdfm
