server:
  port: 443

logs:
  directory: logs

security:
  ssl:
    active: true
    key: privatekey.pem
    ca: intermediate-ca.pem
    cert: certificate.pem

  rateLlmit:
    maxRequest: 1000
    resetAfter: 3600000

  requestTracker:
    maxCache: 5000

service:
  user:
    name: user
    package: loyalty_module_user
    host: 0.0.0.0
    port: 50051

jwt:
  secret: PgSfxfsk0XNS1TbyZYMAvvcVu7KD57cdwZmqlUIVWVrw0RVo0DLOgdqXSgo3ATno7kcAezU2HGtEJ7m53DMvTEkLOgJ0Se90jM7qv3L2Rw5fwy0vkyeZnQyomz1tfWyQapimKdEXDmOuuNt53OKyXreQKZ8gXkG61aAsrAilzPSK0tjqK4fxisS8djtzJbH91YScpPBKiajDlmBan9Lc480d2FajmDiN14DNbehYpZmiu1SY4F3mcnCkQIY6nQm0t1W2gMuoJ2wPW8jB1sGQcBVB2bORXZvtCrjanEca1nlTZLsEyYXJ12XzFRcbb9rrPTBBDoFTM6LuskeuWDrMRkXXDUa5eIYIZIy8aZetRnF3JNS4WGX2I6cjydwktionHOTt0BnkZWnGfIm3

activemq:
  client: loyalty-gateway
  server:
    host: 10.11.30.30
    port: 61613
    login: admin
    passcode: admin
  queues:
    ewalletNotification: /topic/EWALLET_NOTIFY

redis:
  host: 127.0.0.1
  port: 6379
  password: 'password'
  expireIn: 300

pin:
  timeOut: 300
  redirectUrl: http://sandbox.finviet.com.vn:9080/page

otp:
  timeOut: 300

addon:
  fvBackend:
    api: http://sandbox.finviet.com.vn:3980
    version: 2.0

database:
- name: "default"
  type: "mysql"
  logging: true
  synchronize: false
  entities:
  - "dist/entities/*.{js,ts}"
  replication:
    master:
      host: "10.50.50.5"
      port: 3308
      username: "finviet"
      password: "yVREMIiso8BYPBAptGS8"
      database: "loan_referral"
    slaves:
    - host: "10.50.50.5"
      port: 3308
      username: "finviet"
      password: "yVREMIiso8BYPBAptGS8"
      database: "loan_referral"

mafc_api:
  partner_code: 'EXT_FIV'
  input_data_entry:
    url: 'https://apigw.mafc.vn/thirdparty/dataentry'
    username: '3p-mirae'
    password: '3p1qaz@WSX'
  update_data_entry:
    url: 'https://apigw.mafc.vn/3p/v2/data-entry-update'
    username: 'mirae-3p'
    password: '3p1qaz@WSX'
  master_data:
    url: 'https://apigw.mafc.vn/thirdparty/dataentryMD'
    username: '3p-mirae'
    password: '3p1qaz@WSX'
  check_customer_info:
    url: 'https://apigw.mafc.vn/thirdparty/checkcustomer'
    username: '3p-mirae'
    password: '3p1qaz@WSX'
  cic:
    url: 'https://apigw.mafc.vn/cic'
    username: '3p-mirae'
    password: '3p1qaz@WSX'
  upload:
    push_to_und_url: 'https://apigw.mafc.vn/thirdparty/pushundersystem'
    reply_defer_url: 'https://apigw.mafc.vn/thirdparty/pushpenhistory'
    username: '3p-mirae'
    password: '3p1qaz@WSX'

upload:
  backendUrl: http://sandbox.finviet.com.vn:3000/upload
  backendUser: loyalty-user

download:
  backendUrl: http://sandbox.finviet.com.vn:3000/download
  backendUser: loyalty-user
