export enum TransactionType {
  BALANCE = "BALANCE",
  REGISTRATION = "REGISTRATION",
  CREATE_PIN = "CREATE_PIN",
  CHANGE_PIN = "CHANGE_PIN",
  LINK_BANK = "LINK_BANK",
  UNLINK_BANK = "UNLINK_BANK",
  TRANSFER = "TRANSFER",
  CASHIN_VIA_LINKED_BANK = "CASHIN_VIA_LINKED_BANK",
  CASHIN_VIA_UNLINK_BANK = "CASHIN_VIA_UNLINK_BANK",
  CASHOUT_VIA_LINKED_BANK = "CASHOUT_VIA_LINKED_BANK",
  CASHOUT_VIA_UNLINK_BANK = "CASHOUT_VIA_UNLINK_BANK",
  AWAITING_VERIFICATION_CASH_IN_VIA_LINKED_BANK = "AWAITING_VERIFICATION_CASH_IN_VIA_LINKED_BANK"
}
